// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCredential(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddCredential'](arg1, arg2, arg3, arg4);
}

export function CancelBeaconTask(arg1) {
  return window['go']['main']['App']['CancelBeaconTask'](arg1);
}

export function ClearAutomationHistory() {
  return window['go']['main']['App']['ClearAutomationHistory']();
}

export function ClearNetworkDiscoveries(arg1) {
  return window['go']['main']['App']['ClearNetworkDiscoveries'](arg1);
}

export function CloseShell(arg1) {
  return window['go']['main']['App']['CloseShell'](arg1);
}

export function CompleteCommand(arg1, arg2) {
  return window['go']['main']['App']['CompleteCommand'](arg1, arg2);
}

export function CompletePath(arg1, arg2) {
  return window['go']['main']['App']['CompletePath'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateRegistryKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRegistryKey'](arg1, arg2, arg3, arg4);
}

export function DeleteAutomationRule(arg1) {
  return window['go']['main']['App']['DeleteAutomationRule'](arg1);
}

export function DeleteImplantBuild(arg1) {
  return window['go']['main']['App']['DeleteImplantBuild'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteRegistryEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRegistryEntry'](arg1, arg2, arg3, arg4);
}

export function DiscoverNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiscoverNetwork'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadLoot(arg1) {
  return window['go']['main']['App']['DownloadLoot'](arg1);
}

export function GenerateImplant(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GenerateImplant'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GenerateImplantFromProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateImplantFromProfile'](arg1, arg2, arg3);
}

export function GetAliases() {
  return window['go']['main']['App']['GetAliases']();
}

export function GetAutomationHistory() {
  return window['go']['main']['App']['GetAutomationHistory']();
}

export function GetBeaconTaskOutput(arg1) {
  return window['go']['main']['App']['GetBeaconTaskOutput'](arg1);
}

export function GetBeaconTasks(arg1) {
  return window['go']['main']['App']['GetBeaconTasks'](arg1);
}

export function GetBeacons() {
  return window['go']['main']['App']['GetBeacons']();
}

export function GetCertificates() {
  return window['go']['main']['App']['GetCertificates']();
}

export function GetClientConfigs() {
  return window['go']['main']['App']['GetClientConfigs']();
}

export function GetCommandCatalog(arg1) {
  return window['go']['main']['App']['GetCommandCatalog'](arg1);
}

export function GetCredentials() {
  return window['go']['main']['App']['GetCredentials']();
}

export function GetFileList(arg1, arg2) {
  return window['go']['main']['App']['GetFileList'](arg1, arg2);
}

export function GetImplantBuilds() {
  return window['go']['main']['App']['GetImplantBuilds']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetLoot() {
  return window['go']['main']['App']['GetLoot']();
}

export function GetNetworkDiscoveries() {
  return window['go']['main']['App']['GetNetworkDiscoveries']();
}

export function GetOperators() {
  return window['go']['main']['App']['GetOperators']();
}

export function GetPivotListeners() {
  return window['go']['main']['App']['GetPivotListeners']();
}

export function GetPivots() {
  return window['go']['main']['App']['GetPivots']();
}

export function GetProcessList(arg1, arg2) {
  return window['go']['main']['App']['GetProcessList'](arg1, arg2);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetScreenshotData(arg1) {
  return window['go']['main']['App']['GetScreenshotData'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetShellOutput(arg1) {
  return window['go']['main']['App']['GetShellOutput'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWebsites() {
  return window['go']['main']['App']['GetWebsites']();
}

export function InterruptShell(arg1) {
  return window['go']['main']['App']['InterruptShell'](arg1);
}

export function KillAgent(arg1) {
  return window['go']['main']['App']['KillAgent'](arg1);
}

export function KillJob(arg1) {
  return window['go']['main']['App']['KillJob'](arg1);
}

export function KillProcess(arg1, arg2) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2);
}

export function ListAutomationRules() {
  return window['go']['main']['App']['ListAutomationRules']();
}

export function ListCommands() {
  return window['go']['main']['App']['ListCommands']();
}

export function ListRegistrySubKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRegistrySubKeys'](arg1, arg2, arg3);
}

export function ListRegistryValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRegistryValues'](arg1, arg2, arg3);
}

export function MakeDir(arg1, arg2) {
  return window['go']['main']['App']['MakeDir'](arg1, arg2);
}

export function ReadRegistryValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadRegistryValue'](arg1, arg2, arg3, arg4);
}

export function RegenerateImplant(arg1) {
  return window['go']['main']['App']['RegenerateImplant'](arg1);
}

export function RemoveBeacon(arg1) {
  return window['go']['main']['App']['RemoveBeacon'](arg1);
}

export function RemoveCredential(arg1) {
  return window['go']['main']['App']['RemoveCredential'](arg1);
}

export function RemoveLoot(arg1) {
  return window['go']['main']['App']['RemoveLoot'](arg1);
}

export function RemoveNetworkDiscoveries(arg1, arg2) {
  return window['go']['main']['App']['RemoveNetworkDiscoveries'](arg1, arg2);
}

export function RemovePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemovePath'](arg1, arg2, arg3);
}

export function RenameAgent(arg1, arg2) {
  return window['go']['main']['App']['RenameAgent'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2, arg3);
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function RunAutomationRule(arg1, arg2) {
  return window['go']['main']['App']['RunAutomationRule'](arg1, arg2);
}

export function RunSessionCommand(arg1, arg2) {
  return window['go']['main']['App']['RunSessionCommand'](arg1, arg2);
}

export function SaveAutomationRule(arg1) {
  return window['go']['main']['App']['SaveAutomationRule'](arg1);
}

export function SaveProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetAutomationRuleEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAutomationRuleEnabled'](arg1, arg2);
}

export function StartListener(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartListener'](arg1, arg2, arg3, arg4);
}

export function StartShell(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartShell'](arg1, arg2, arg3, arg4, arg5);
}

export function TakeScreenshot(arg1) {
  return window['go']['main']['App']['TakeScreenshot'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function UploadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2, arg3);
}

export function WriteRegistryValue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['WriteRegistryValue'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function WriteShell(arg1, arg2) {
  return window['go']['main']['App']['WriteShell'](arg1, arg2);
}
