// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {clientpb} from '../models';
import {sliverpb} from '../models';

export function AddCredential(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CancelBeaconTask(arg1:string):Promise<void>;

export function ClearAutomationHistory():Promise<void>;

export function ClearNetworkDiscoveries(arg1:string):Promise<void>;

export function CloseShell(arg1:string):Promise<void>;

export function CompleteCommand(arg1:string,arg2:string):Promise<Array<string>>;

export function CompletePath(arg1:string,arg2:string):Promise<Array<string>>;

export function Connect(arg1:string):Promise<void>;

export function CreateRegistryKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteAutomationRule(arg1:string):Promise<void>;

export function DeleteImplantBuild(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRegistryEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DiscoverNetwork(arg1:string,arg2:string,arg3:string):Promise<Array<main.NetworkDiscovery>>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function DownloadLoot(arg1:string):Promise<string>;

export function GenerateImplant(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:number):Promise<string>;

export function GenerateImplantFromProfile(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetAliases():Promise<any>;

export function GetAutomationHistory():Promise<Array<main.AutomationRun>>;

export function GetBeaconTaskOutput(arg1:string):Promise<string>;

export function GetBeaconTasks(arg1:string):Promise<clientpb.BeaconTasks>;

export function GetBeacons():Promise<clientpb.Beacons>;

export function GetCertificates():Promise<clientpb.CertificateInfo>;

export function GetClientConfigs():Promise<Array<string>>;

export function GetCommandCatalog(arg1:string):Promise<main.CommandCatalog>;

export function GetCredentials():Promise<clientpb.Credentials>;

export function GetFileList(arg1:string,arg2:string):Promise<sliverpb.Ls>;

export function GetImplantBuilds():Promise<clientpb.ImplantBuilds>;

export function GetJobs():Promise<clientpb.Jobs>;

export function GetLoot():Promise<clientpb.AllLoot>;

export function GetNetworkDiscoveries():Promise<Array<main.NetworkDiscovery>>;

export function GetOperators():Promise<clientpb.Operators>;

export function GetPivotListeners():Promise<Array<main.PivotListenerSnapshot>>;

export function GetPivots():Promise<clientpb.PivotGraph>;

export function GetProcessList(arg1:string,arg2:boolean):Promise<sliverpb.Ps>;

export function GetProfiles():Promise<clientpb.ImplantProfiles>;

export function GetScreenshotData(arg1:string):Promise<string>;

export function GetSessions():Promise<clientpb.Sessions>;

export function GetShellOutput(arg1:string):Promise<string>;

export function GetVersion():Promise<clientpb.Version>;

export function GetWebsites():Promise<clientpb.Websites>;

export function InterruptShell(arg1:string):Promise<boolean>;

export function KillAgent(arg1:string):Promise<void>;

export function KillJob(arg1:number):Promise<void>;

export function KillProcess(arg1:string,arg2:number):Promise<void>;

export function ListAutomationRules():Promise<Array<main.AutomationRule>>;

export function ListCommands():Promise<Array<string>>;

export function ListRegistrySubKeys(arg1:string,arg2:string,arg3:string):Promise<sliverpb.RegistrySubKeyList>;

export function ListRegistryValues(arg1:string,arg2:string,arg3:string):Promise<sliverpb.RegistryValuesList>;

export function MakeDir(arg1:string,arg2:string):Promise<void>;

export function ReadRegistryValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.RegistryValue>;

export function RegenerateImplant(arg1:string):Promise<string>;

export function RemoveBeacon(arg1:string):Promise<void>;

export function RemoveCredential(arg1:string):Promise<void>;

export function RemoveLoot(arg1:string):Promise<void>;

export function RemoveNetworkDiscoveries(arg1:string,arg2:Array<string>):Promise<void>;

export function RemovePath(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RenameAgent(arg1:string,arg2:string):Promise<void>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RunAutomationRule(arg1:string,arg2:string):Promise<void>;

export function RunSessionCommand(arg1:string,arg2:string):Promise<string>;

export function SaveAutomationRule(arg1:main.AutomationRule):Promise<main.AutomationRule>;

export function SaveProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:number):Promise<void>;

export function SetAutomationRuleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartListener(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function StartShell(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:number):Promise<main.ShellInfo>;

export function TakeScreenshot(arg1:string):Promise<string>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;

export function UploadFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function WriteRegistryValue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function WriteShell(arg1:string,arg2:string):Promise<void>;
